[versions]
agp = "8.13.2"
kotlin = "2.3.20"
activityCompose = "1.13.0"
compose = "1.10.3"
coroutines = "1.10.2"
serialization = "1.11.0"
caterktor = "0.1.0"
mviKotlin = "3.3.0"
decompose = "2.1.4-compose-experimental"
essenty = "1.2.0"
sqlDelight = "2.2.1"
koin = "4.1.1"
imageLoader = "1.7.1"
kotlinWrappersBom = "1.0.0-pre.641"
touchlab = "2.0.5"
compileSdk = "36"
targetSdk = "36"
minSdk = "24"
appMajorVersion = "1"
appMinorVersion = "0"
appPatchVersion = "0"
appVersionCode = "1"

[libraries]
# Org.JetBrains.Kotlinx
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# Org.JetBrains.KotlinWrappers
kotlin-wrappers-bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version.ref = "kotlinWrappersBom" }
kotlin-styled = { module = "org.jetbrains.kotlin-wrappers:kotlin-styled" } # Uses BOM

# Androidx.Activity
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

# CaterKtor
caterktor-core = { module = "io.github.oyedsamu:caterktor-core", version.ref = "caterktor" }
caterktor-ktor = { module = "io.github.oyedsamu:caterktor-ktor", version.ref = "caterktor" }
caterktor-logging = { module = "io.github.oyedsamu:caterktor-logging", version.ref = "caterktor" }
caterktor-serialization-json = { module = "io.github.oyedsamu:caterktor-serialization-json", version.ref = "caterktor" }
caterktor-engine-okhttp = { module = "io.github.oyedsamu:caterktor-engine-okhttp", version.ref = "caterktor" }
caterktor-engine-darwin = { module = "io.github.oyedsamu:caterktor-engine-darwin", version.ref = "caterktor" }
caterktor-engine-cio = { module = "io.github.oyedsamu:caterktor-engine-cio", version.ref = "caterktor" }
caterktor-testing = { module = "io.github.oyedsamu:caterktor-testing", version.ref = "caterktor" }

# CashApp.SQLDelight
sqldelight-gradle-plugin = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqlDelight" } # This is a plugin, will also add to [plugins]
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqldelight-sqljs-driver = { module = "app.cash.sqldelight:sqljs-driver", version.ref = "sqlDelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqlDelight" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

# ArkIvanov.MVIKotlin
mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mviKotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mviKotlin" }
mvikotlin-extensions-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mviKotlin" }

# ArkIvanov.Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }

# ArkIvanov.Essenty
essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

# Github
imageLoader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoader" }

# Touchlab
touchlab-stately-common = { module = "co.touchlab:stately-common", version.ref = "touchlab" }


[plugins]
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
